project:
  type: website

website:
  title: "Russell Goebel"
  navbar:
    title: "Russell Goebel"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Writing
      - href: projects.qmd
        text: Projects
  page-footer:
    left: "© Russell Goebel 2026"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true